FROM golang:1.22

WORKDIR /app

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN go build -o consumer-server

CMD ["/wait-for-it.sh", "rabbitmq:5672", "--timeout=30", "--", "/wait-for-it.sh", "postgres:5432", "--timeout=30", "--", "./consumer-server"]
