FROM golang:1.22

WORKDIR /app

# wait-for-it.sh'yi kopyala ve çalıştırma izni ver
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN go build -o api-server

# RabbitMQ ve PostgreSQL hazır olana kadar bekle, sonra api-server'ı başlat
CMD ["/wait-for-it.sh", "rabbitmq:5672", "--timeout=30", "--", "/wait-for-it.sh", "postgres:5432", "--timeout=30", "--", "./api-server"]